server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: flight-service
          uri: lb://flight-service
          predicates:
            - Path=/api/flight/**

        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/api/booking/**

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notification/**
