server:
  port: 8082

spring:
  application:
    name: booking-service

  cloud:
    config:
      uri: http://localhost:8888

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  r2dbc:
    url: r2dbc:mysql://localhost:3306/bookingdb
    username: root
    password: root

  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
