server:
  port: 8082

spring:
  application:
    name: booking-service

  config:
    import: "optional:configserver:http://localhost:8888/"

  datasource:
    url: jdbc:mysql://localhost:3306/booking_db
    username: root
    password: Root@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest

rabbitmq-config:
  exchange: booking.exchange
  queue: booking.email.queue
  routing-key: booking.email.key

resilience4j:
  circuitbreaker:
    instances:
      flightServiceCb:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s

