spring:
  application:
    name: booking-service

  datasource:
    url: jdbc:mysql://localhost:3306/booking_db
    username: booking_user
    password: booking_pwd
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
