server:
  port: 8082

spring:
  application:
    name: booking-service

  config:
    import: "optional:configserver:http://localhost:8888"

  datasource:
    url: jdbc:mysql://localhost:3306/bookingdb
    username: root
    password: Root@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  # Kafka producer for BookingEvent (producer config is also in common application.yml)
  kafka:
    consumer:
      group-id: booking-service-group
      auto-offset-reset: earliest

# Used by your @Value("${kafka.topics.booking-created}")
kafka:
  topics:
    booking-created: booking.created

booking:
  email:
    exchange: booking.exchange
    routing-key: booking.email
    queue: booking.email.queue

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"

resilience4j:
  circuitbreaker:
    instances:
      flightServiceClient:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
