server:
  port: 8082

spring:
  application:
    name: booking-service

  datasource:
    url: jdbc:mysql://localhost:3306/booking_db
    username: root
    password: Root@123
    driver-class-name: com.mysql.cj.jdbc.Driver

# ... (your JPA / hibernate stuff can stay)

booking:
  email:
    exchange: booking.exchange
    queue: booking.email.queue
    routing-key: booking.email.key

resilience4j:
  circuitbreaker:
    instances:
      flightServiceCb:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
