server:
  port: 8082

spring:
  application:
    name: booking-service

  config:
    import: "optional:configserver:http://localhost:8888"

  datasource:
    url: jdbc:mysql://localhost:3306/bookingdb
    username: root
    password: "Root@123"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect

  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

