spring:
  application:
    name: flight-service

  r2dbc:
    url: r2dbc:pool:mysql://localhost:3306/flights_db
    username: flight_user
    password: flight_pwd

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
