server:
  port: 8083

spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/flightdb
    username: root
    password: tathagya2003

  sql:
    init:
      mode: always

  cache:
    type: redis

  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    root: INFO
    org.springframework.r2dbc: DEBUG
    com.flightapp.flightservice: DEBUG

eureka:
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

resilience4j:
  circuitbreaker:
    instances:
      flightSearchCB:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
