server:
  port: 8083

spring:
  application:
    name: notification-service

  config:
    import: "optional:configserver:http://localhost:8888"

  mail:
    host: smtp.gmail.com
    port: 587
    username: akankshyap1402@gmail.com
    password: pthy wsur endm lydd
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
