server:
  port: 8083

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  level:
    root: INFO
    com.flightapp.notificationservice: DEBUG

eureka:
  instance:
    prefer-ip-address: true

rabbitmq:
  exchange: booking.exchange
  queue: booking.email.queue
  routing-key: booking.email.key
