server:
  port: 8083

spring:
  application:
    name: notification-service

  config:
    import: "optional:configserver:http://localhost:8888"

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  mail:
    host: smtp.gmail.com
    port: 587
    username: akankshyap1402@gmail.com
    password: pthy wsur endm lydd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

booking:
  email:
    exchange: booking.exchange
    routing-key: booking.email
    queue: booking.email.queue

kafka:
  topics:
    booking-created: booking.created

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
