server:
  port: 8083

spring:
  application:
    name: notification-service

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: booking-events-group
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"

logging:
  level:
    root: INFO
    com.flightapp.notificationservice: DEBUG

eureka:
  instance:
    prefer-ip-address: true

booking:
  email:
    exchange: booking.exchange
    queue: booking.email.queue
    routing-key: booking.email.key
